# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
data = np.loadtxt("data/minutes_n_ingredients.csv",dtype=np.int32, delimiter=',', skiprows=1)
data[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
# Среднее значение
#data_2 = np.delete(data, 0, axis=1)
data_2 = data[:, 1:]

average_value = np.mean(data_2,axis=0)
average_value
# np.delete(average_value, 0)

array([2.16010017e+04, 9.05528000e+00])

In [3]:
# Минимальное значение
data_2.min(axis=0)

array([0, 1])

In [4]:
# Максимальное значение
data_2.max(axis=0)

array([2147483647,         39])

In [5]:
# Медиана
np.median(data_2, axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
#data_3 = np.delete(data_2, 1, axis=1)
data_3 = data[:, 1:2]
np.quantile(data_3, 0.75)

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [7]:
# подсчет кол-ва рецептов, продолжительность которых равна 0
zero_value = np.where(data_3 == 0)
# print(zero_value)
quantity_of_zero_elements = zero_value[0].size
quantity_of_zero_elements

479

In [8]:
#замена 0 на 1
print(data_3[691])
data_3[data_3 == 0 ] = 1
print(data_3[691])
print(data_3)

[0]
[1]
[[ 60]
 [ 25]
 [ 10]
 ...
 [ 65]
 [  5]
 [140]]


 5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [9]:
#проверка количества уникальных ай ди
data_4 = data[:, 0]
len(np.unique(data_4))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [10]:
data_5 = data[:, 2]
print (len(np.unique(data_5)))
print(np.unique(data_5))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [11]:
recipies = np.where(data[:, 2] <= 5) [0]
# print(recipies)
# print(data)
recipes_1 = data[recipies]
print(recipes_1)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [12]:
#np.divide(data_5, data_3, dtype='float64')
data_3 = data[:, 1:2]
data_5 = data[:, 2:]
# print(data_5)
# print(data_3)
(np.divide(data_5, data_3, dtype='float64'))
#delenie = data_5/data_3


array([[0.26666667],
       [0.28      ],
       [0.6       ],
       ...,
       [0.23076923],
       [0.8       ],
       [0.1       ]])

In [13]:
np.divide(data_5, data_3, dtype='float64').max(axis=0)

array([24.])

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [14]:
data_type = np.dtype([('id', int), ('minutes', int), ('ingridients', int)])
a = np.loadtxt("data/minutes_n_ingredients.csv", dtype=data_type, delimiter=',', skiprows=1)
#print(a)
reverse_order = np.sort(a, order='minutes') [::-1]
#print(reverse_order) 
top100 = reverse_order[0:100]
print(top100['ingridients'])
mean = np.mean(top100['ingridients'])
print(mean)

[ 8  7  2  4  7  5  3  3  5  5  4  2  9  2  4  3  2  3  3  7  5  4  3 22
  4 15  8  3  2 17  3  9  3  5  7  3  8  6  5  4  5  6  4  2  8  6  8  6
  8  3  4  4 10 11 12 11  4  4  5  9  7 12 10  5  9  6  3  6  4  9 13  2
  3  6  5 13  8  5  5 10 13 17  8  5  8  8  3  8 14  3  8 12 13  8  7  6
  7  8  4  6]
6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
random_10 = np.random.choice(a, size=10, replace=False)
print (random_10)

[(369551,   6,  4) (477672,  30, 10) (236012,  90, 14) (349478, 485,  6)
 (207985,  25,  8) (122471, 135,  2) ( 81197,  30,  8) (105207,  70,  5)
 (386348,  45,  5) (178783,  15, 13)]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
mean = np.mean(a['ingridients'])
indexes_less_then_half = np.where(a["ingridients"] < mean)[0]
# print(indexes_less_then_half)
indexes_quntity_less_then_half = indexes_less_then_half.size
total_indexes = a.size
# print(indexes_quntity_less_then_half)
# print(total_indexes)
percents = indexes_quntity_less_then_half/(total_indexes/100)
print(percents)
# В таблице строчка будет индекс + 2

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [17]:
data = np.loadtxt("data/minutes_n_ingredients.csv",dtype=np.int32, delimiter=',', skiprows=1)

data_with_zeros = np.insert(data, 3 , 0, axis=1)
indexes_simple = np.where((data_with_zeros[:, 1] <= 20) & (data_with_zeros[:, 2] <= 5))
data_with_zeros[indexes_simple, 3] = 1
# print(indexes_simple)
print(data_with_zeros)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [18]:
indexes_quntity_simple = indexes_simple[0].size
# print(indexes_quntity_simple)
# print(total_indexes)
percents = indexes_quntity_simple/(total_indexes/100)
print(percents)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
data = np.loadtxt("data/minutes_n_ingredients.csv", dtype=np.int32, delimiter=',', skiprows=1)

indexes_short = np.where(data[:, 1] < 10)[0]
indexes_standart = np.where((data[:, 1] >= 10) & ((data[:, 1] < 20)))[0]
indexes_long = np.where(data[:, 1] >= 20)[0]
data_short = data[indexes_short]
data_standart = data[indexes_standart]
data_long = data[indexes_long]

data_standart_min = data_standart[0:indexes_short.size]
data_long_min = data_long[0:indexes_short.size]

data_short_exp = np.expand_dims(data_short, axis=(0))
data_standart_exp = np.expand_dims(data_standart_min, axis=(0))

data_long_exp = np.expand_dims(data_long_min, axis=(0))

three_dem = np.vstack([data_short_exp, data_standart_exp, data_long_exp])
print(three_dem)
# print(three_dem.shape)


[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
